require("options/lualine-config")
require("options/telescope-config")
require("options/harpoon-config")
require("options/vim-config")
require("options/lsp-config")
require("options.toggleterm-config")
require("options.treesitter-config")
